### ISSUE TITLE
Missing Invisibility rune magic spell

### ISSUE THREAD

**Issue by jetuk** [sun-dragon-cult/fvtt-system-rqg#538] opened 2023-05-18 21:07 UTC
### _What_: Describe the bug

Invisibility rune magic spell is missing from the compendium.

### _How:_ To Reproduce

Search for Invisibility. It's not there :(

### Expected behavior

It should be there!

### Screenshots

![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/4604654/87289d9b-c1e5-4ee3-9a98-717d3a8d4bc0)

### Environment - please paste the information from foundry settings tab "support" button:

```
Foundry Virtual Tabletop: Version 10, 10.291
Game System: rqg, 2.1.2
Active Modules: 0
Performance Mode: 2

OS: Linux x86_64
Client: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0
GPU: Radeon R9 200 Series
Max Texture Size: 16384

Scene: 22500 x 11316.065276116666 | Grid Size: 50 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 2

Actors: 3 | Items: 137 | Journal: 2 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 48 | Chat Messages: 16
```

### Additional context

None.

**Comment by Moonpile** [comment] 2023-05-18 23:32
Thanks for the feedback!  It's kind of funny that you can't see "invisibility"!

The system release includes only the material that is freely available on the RuneQuest Wiki: https://rqwiki.chaosium.com/rules/rune-spells.html

If you see things that are missing compared to the RQG book or Red Book of Magic or anything and it's not also on the wiki that's probably by design.

**Comment by wake42** [comment] 2023-05-19 21:16
I'm closing this issue since that spell is not part of the wiki (and therefor not part of the base system)

**Closed by wake42** 2023-05-19 21:16 UTC
Labels: type: bug
