### ISSUE TITLE
Natural Weapons that do not  have a damage bonus applied

### ISSUE THREAD

**Issue by Lockbox313** [sun-dragon-cult/fvtt-system-rqg#532] opened 2023-05-05 17:06 UTC
### _Why:_ Is your feature request related to a problem?
Some attack types like Trample do not have damage bonus applied another example is Horse bite .

### _What:_ Describe the solution you'd like

Another checkbox similar to the checkbox for missile weapon damage bonus application.

**Comment by wake42** [comment] 2023-05-12 10:51
Thanks for the case - we have a refactor of the weapon item planned to address this and potentially other cases that the current weapon items can't model see #106 & #497. I'm closing this case as a duplicate of those issues.

**Closed by wake42** 2023-05-12 10:51 UTC
Labels: type: feature
